### NumPy experiment

In [1]:
import numpy as np


In [5]:
numClass = 5
numTraining = 10
numDimension = 12

X = np.arange(120)
X.shape = (numTraining, numDimension)
X

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [6]:
W = np.arange(60)
W.shape = (numDimension, numClass)
W = W * 0.1
W

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4],
       [2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4],
       [3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4],
       [4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4],
       [5.5, 5.6, 5.7, 5.8, 5.9]])

In [7]:
Y = np.arange(10)
Y.shape = (numTraining,)
Y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
Y[-5:] = Y[0:5]
Y

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [46]:
scores = X.dot(W)
scores

array([[ 253. ,  259.6,  266.2,  272.8,  279.4],
       [ 649. ,  670. ,  691. ,  712. ,  733. ],
       [1045. , 1080.4, 1115.8, 1151.2, 1186.6],
       [1441. , 1490.8, 1540.6, 1590.4, 1640.2],
       [1837. , 1901.2, 1965.4, 2029.6, 2093.8],
       [2233. , 2311.6, 2390.2, 2468.8, 2547.4],
       [2629. , 2722. , 2815. , 2908. , 3001. ],
       [3025. , 3132.4, 3239.8, 3347.2, 3454.6],
       [3421. , 3542.8, 3664.6, 3786.4, 3908.2],
       [3817. , 3953.2, 4089.4, 4225.6, 4361.8]])

In [65]:
#correct_scores =scores[list(range(numTraining)), Y]
correct_scores = scores[np.arange(numTraining), Y]
correct_scores = correct_scores.reshape(numTraining, -1)
correct_scores

array([[ 253. ],
       [ 670. ],
       [1115.8],
       [1590.4],
       [2093.8],
       [2233. ],
       [2722. ],
       [3239.8],
       [3786.4],
       [4361.8]])

In [69]:
margin = IF (scores - correct_scores) <= 0 0: (scores - correct_scores)
margin

SyntaxError: invalid syntax (<ipython-input-69-e6a00135602c>, line 1)

In [63]:
loss = np.amax(margin, 1)
loss

TypeError: only integer scalar arrays can be converted to a scalar index