### NumPy experiment

In [41]:
import numpy as np


In [42]:
num_classes = 5
num_train = 10
num_dimension = 12

X = np.arange(120)
X.shape = (num_train, num_dimension)
X

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [43]:
W = np.arange(60)
W.shape = (num_dimension, num_classes)
W = W * 0.1
W

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4],
       [2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4],
       [3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4],
       [4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4],
       [5.5, 5.6, 5.7, 5.8, 5.9]])

In [44]:
y = np.arange(10)
y.shape = (num_train,)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
y[-5:] = y[0:5]
y

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [46]:
dW = np.zeros(W.shape) # initialize the gradient as zero
loss = 0.0
for i in range(num_train):
    scores = X[i].dot(W)
    # print(i, scores)
    correct_class_score = scores[y[i]]
    # print(correct_class_score)
    # margin_loss_count = 0
    for j in range(num_classes):
      if j == y[i]:
        continue
      print(i, j)
      margin = scores[j] - correct_class_score + 1 # note delta = 1
      print('score[',j,']', scores[j],'correct class score', correct_class_score, 'margin', margin)
      if margin > 0:
        loss += margin
        # margin_loss_count += 1
        # Computing the gradient analytically with Calculus
        # For incorrect classes
        dW[:, j] += X[i] # add X value to classes that are incorrect
        dW[:, y[i]] -= X[i] # subtract X value from the correct class
        print(i, j, dW)
    # For correct classes
    # dW[:, y[i]] += -1 * margin_loss_count * X[i]

    
# Right now the loss is a sum over all training examples, but we want it
# to be an average instead so we divide by num_train.
loss /= num_train
dW /= num_train

print('loss', loss)
print('dW', dW)

# Add regularization to the loss.
# loss += reg * np.sum(W * W)
# that contribues to the gradient as well

reg = 1

# dW += 2 * reg * W
dW += reg * W  # regularize the weights
# Add regularization to the loss.
loss += 0.5 * reg * np.sum(W * W)

print('loss', loss)
print('dW', dW)


0 1
score[ 1 ] 259.6 correct class score 253.0 margin 7.600000000000023
0 1 [[  0.   0.   0.   0.   0.]
 [ -1.   1.   0.   0.   0.]
 [ -2.   2.   0.   0.   0.]
 [ -3.   3.   0.   0.   0.]
 [ -4.   4.   0.   0.   0.]
 [ -5.   5.   0.   0.   0.]
 [ -6.   6.   0.   0.   0.]
 [ -7.   7.   0.   0.   0.]
 [ -8.   8.   0.   0.   0.]
 [ -9.   9.   0.   0.   0.]
 [-10.  10.   0.   0.   0.]
 [-11.  11.   0.   0.   0.]]
0 2
score[ 2 ] 266.20000000000005 correct class score 253.0 margin 14.200000000000045
0 2 [[  0.   0.   0.   0.   0.]
 [ -2.   1.   1.   0.   0.]
 [ -4.   2.   2.   0.   0.]
 [ -6.   3.   3.   0.   0.]
 [ -8.   4.   4.   0.   0.]
 [-10.   5.   5.   0.   0.]
 [-12.   6.   6.   0.   0.]
 [-14.   7.   7.   0.   0.]
 [-16.   8.   8.   0.   0.]
 [-18.   9.   9.   0.   0.]
 [-20.  10.  10.   0.   0.]
 [-22.  11.  11.   0.   0.]]
0 3
score[ 3 ] 272.8 correct class score 253.0 margin 20.80000000000001
0 3 [[  0.   0.   0.   0.   0.]
 [ -3.   1.   1.   1.   0.]
 [ -6.   2.   2.   2.   0.]


In [48]:
X = np.arange(120)
X.shape = (num_train, num_dimension)

scores = X.dot(W)
scores

W = np.arange(60)
W.shape = (num_dimension, num_classes)
W = W * 0.1
W

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4],
       [2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4],
       [3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4],
       [4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4],
       [5.5, 5.6, 5.7, 5.8, 5.9]])

In [49]:
#correct_scores =scores[list(range(numTraining)), y]
correct_class_score = scores[np.arange(num_train), y]
# correct_class_score = correct_scores.reshape(num_train, -1)
# correct_class_score

margins = np.maximum(0, scores - correct_class_score[:, np.newaxis] + delta)
margins[np.arange(num_train), y] = 0
loss = np.sum(margins)
print("margins", margins)
print("loss", loss)

NameError: name 'delta' is not defined

In [12]:
margin = scores - correct_scores
margin

array([[   0. ,    6.6,   13.2,   19.8,   26.4],
       [ -21. ,    0. ,   21. ,   42. ,   63. ],
       [ -70.8,  -35.4,    0. ,   35.4,   70.8],
       [-149.4,  -99.6,  -49.8,    0. ,   49.8],
       [-256.8, -192.6, -128.4,  -64.2,    0. ],
       [   0. ,   78.6,  157.2,  235.8,  314.4],
       [ -93. ,    0. ,   93. ,  186. ,  279. ],
       [-214.8, -107.4,    0. ,  107.4,  214.8],
       [-365.4, -243.6, -121.8,    0. ,  121.8],
       [-544.8, -408.6, -272.4, -136.2,    0. ]])

In [13]:
margin = np.maximum(0, scores - correct_scores + 1)
margin

array([[  1. ,   7.6,  14.2,  20.8,  27.4],
       [  0. ,   1. ,  22. ,  43. ,  64. ],
       [  0. ,   0. ,   1. ,  36.4,  71.8],
       [  0. ,   0. ,   0. ,   1. ,  50.8],
       [  0. ,   0. ,   0. ,   0. ,   1. ],
       [  1. ,  79.6, 158.2, 236.8, 315.4],
       [  0. ,   1. ,  94. , 187. , 280. ],
       [  0. ,   0. ,   1. , 108.4, 215.8],
       [  0. ,   0. ,   0. ,   1. , 122.8],
       [  0. ,   0. ,   0. ,   0. ,   1. ]])

In [14]:
margin[np.arange(num_train), y] = 0
margin

array([[  0. ,   7.6,  14.2,  20.8,  27.4],
       [  0. ,   0. ,  22. ,  43. ,  64. ],
       [  0. ,   0. ,   0. ,  36.4,  71.8],
       [  0. ,   0. ,   0. ,   0. ,  50.8],
       [  0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,  79.6, 158.2, 236.8, 315.4],
       [  0. ,   0. ,  94. , 187. , 280. ],
       [  0. ,   0. ,   0. , 108.4, 215.8],
       [  0. ,   0. ,   0. ,   0. , 122.8],
       [  0. ,   0. ,   0. ,   0. ,   0. ]])

In [16]:
loss = np.sum(margin) / num_train
loss

215.59999999999997

In [ ]:
incorrect_mask = 